# ==============================================================
#							A_MAZE_ING
# ==============================================================

NAME = A_MAZE_ING

install:
	mkdir -p ~/miniconda3
	wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
	bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
	rm ~/miniconda3/miniconda.sh
	source ~/miniconda3/bin/activate
	conda init --all
	conda install -c conda-forge xcb-util-keysyms
	export C_INCLUDE_PATH=$CONDA_PREFIX/include
	export LIBRARY_PATH=$CONDA_PREFIX/lib
	-C mlx_CLXV make
